language: node_js
node_js:
  - "lts/*"
script: npm run build
before_deploy:
  - sudo apt-get install sshpass
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
    condition: $TRAVIS_TEST_RESULT = 0