language: node_js
node_js:
- lts/*
addons:
  apt:
    packages:
    - sshpass

# Create production build
script: npm run build

before_install:
- openssl aes-256-cbc -K $encrypted_9df4efaa7c2d_key -iv $encrypted_9df4efaa7c2d_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

# Get public key from server and add to known hosts
before_deploy:
- sudo apt-get install sshpass
- ssh-keyscan -H $SERVER_URL 2>&1 | tee -a $HOME/.ssh/known_hosts

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_TEST_RESULT = 0
